<?php

define('CATALOG_ID', 4);
define('MATERIALS_SECTION_ID', 2);
define('VELCOM', '+375 (29) 182-27-46');
define('MTS', '+375 (33) 666-50-24');

//define('NEED_PROPS', ["PROP_CONSTANSE", "PROP_COLOuR", "PROP_CARTS", "PROP_SIZE", "DIAMETER", "CONCENTRATE"]);

const NEED_PROPS = ["PROP_COLOuR", "CARTRIDGES", "PROP_SIZE", "DIAMETER", "CONCENTRATE", "QUANTITY", "AMOUNT"];


const NEED_PROPS_BASKET = ["PROPERTY_PROP_COLOUR_VALUE",
    "PROPERTY_PROP_SIZE_VALUE", "PROPERTY_DIAMETER_VALUE", "PROPERTY_VOLUME_VALUE", "PROPERTY_QUANTITY_VALUE", "PROPERTY_AMOUNT_VALUE"];
